### ISSUE TITLE
Remove BASE_URL

### ISSUE THREAD

**Issue by atinux** [vuchl/nuxt-micro-template#2]
Hi,

I just made changes to nuxt/express to remove the BASE_URL env variable so the user doesn't have to specify it anymore :)

Changes: https://github.com/nuxt/express/commit/95a9867b1108777932779c4fc46ef0a0522811b5

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/micro-template/issues/c2">#c2</a>)</em></sub></div>

**Comment by vuchl** [comment]
You mean here, right?
https://github.com/vuchl/nuxt-micro-template/blob/master/template/nuxt.config.js#L24

**Comment by atinux** [comment]
See #3
