### ISSUE TITLE
Transfert to Nuxt Community

### ISSUE THREAD

**Issue by atinux** [vuchl/nuxt-micro-template#5]
Hi @vuchl 

It was nice meeting you at VueConf!

Could you transfer the project to nuxt community? If you don't know how to, you can add me as an admin for this project so I can transfert it for you :)

Thank you

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/micro-template/issues/c3">#c3</a>)</em></sub></div>

**Comment by vuchl** [comment]
Hey @Atinux!

I'll look into the project and propably create a version for v2. I'll transfer it when I got it working!

Regards Sebastian

**Comment by atinux** [comment]
Awesome!

**Comment by vuchl** [comment]
Hey @Atinux!

Since my template is a fork of nuxtjs/express-template i get this message when trying to transfer:
nuxt-community already has a repository in the nuxt-community/express-template network

Any ideas?

**Comment by atinux** [comment]
Could you give me write access directly on this repo so I can try @vuchl?

Also, from now I receive an email eveytime your mention me on Github so I will be able to answer you faster.

**Comment by vuchl** [comment]
I added you as a collaborateur if this is what i'd need to do

**Comment by atinux** [comment]
Could you give me admin right @vuchl ?

**Comment by vuchl** [comment]
How? Transfer it to you?

**Comment by atinux** [comment]
No I guess you can give me admin access to your repository so I can try to remove the fork and then transfer it to `nuxt-community` :)

**Comment by vuchl** [comment]
I searched around but can not find anything more thn collaborateur access. and removing the fork information is done via github support. I'll ask them.

**Comment by atinux** [comment]
@vuchl this is where I can do it with nuxt.js repository, I guess you should have the same UI

![screenshot_2017-07-10_10-37-07](https://user-images.githubusercontent.com/904724/28009453-cd04299c-655b-11e7-8dad-8a60f5e5492b.png)

**Comment by vuchl** [comment]
Sadly not:
![2017-07-10 10_41_56-clipboard](https://user-images.githubusercontent.com/4921147/28009697-9fad3b54-655c-11e7-9a79-13897e5668c9.png)

**Comment by atinux** [comment]
Indeed you might need to wait for Github support to remove the fork :/

**Comment by vuchl** [comment]
Hey @Atinux!

I asked them to detach it from the parent. I'll update the README to include the hint. Since I think its essential that the idea is not my own.

**Comment by vuchl** [comment]
Transfer done :heavy_check_mark:

**Comment by atinux** [comment]
:confetti_ball:
