### ISSUE TITLE
Template section not output in vue files

### ISSUE THREAD

**Issue by mickdekkers** [vuchl/nuxt-micro-template#7]
When I used the template, for some reason the vue files it created did not have `<template>` sections.
Looking at the source, it seems to use some kind of `{{{{raw}}}}` helper, presumably the one in `meta.json`.

If I had to guess, I'd say that function is returning undefined or perhaps an empty string.

Using vue-cli v2.9.1

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/micro-template/issues/c4">#c4</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Maybe you have a version of handlebars installed globally that is older than custom helpers?
I just tried it.
```sh
vue --version
#> 2.9.1
```
```sh
vue init nuxt-community/micro-template test && cd test && cat pages/index.vue
```
produces the desired output, including the template with uninterpolated  vue `{{}}`.
Was it all of the `.vue` files or just some?
What node version?

The same function is used in the express template.

**Comment by mickdekkers** [comment]
Oh sorry I forgot to mention, my node version is 8.7.0 and I'm on Windows 10 64-bit.
It happened for all the vue files that use the helper.
As far as I can tell (through `yarn global list` and `npm ls -g --depth 0`) I don't have handlebars installed globally.

I ran the command you posted and I'm not seeing a template section, so at least it's reproducible.
```
   vue-cli · Generated "test".

   To get started:

     cd test
     npm install # Or yarn
     npm run dev # Or yarn dev

<script>
import axios from '~/plugins/axios'

export default {
  data () {
    return {
      users: []
    }
  },
  async asyncData () {
    const {data} = await axios.get('/api/users')
    return {users: data}
  },
  head () {
    return {
      title: 'Users'
    }
  }
}
</script>

<style scoped>
.title
{
  margin: 30px 0;
}
.users
{
  list-style: none;
  margin: 0;
  padding: 0;
}
.user
{
  margin: 10px 0;
}
</style>
```

**Comment by qm3ster** [comment]
I updated from 8.4.0 to 8.7.0 and still don't have the problem.
I am on Ubuntu GNOME 17.04 though.

**Comment by qm3ster** [comment]
@mickdekkers please sign off here if you resolve the issue or have any new information.

**Comment by mickdekkers** [comment]
Alright, I'll let you know if I discover anything new.

**Comment by vuchl** [comment]
I'll take a look tomorrow. But it's definately coming from `vue-cli` and the templating system. we had a similar issue before here #4 

First edit:
```bash
$ node -v
8.7.0

$ npm -v
5.4.2

$ npm i -g npm
...
+ npm@5.5.1

$ npm i -g vue-cli

$ vue -V
2.9.1

$ vue init nuxt-community/nuxt-micro-template numi
```

The ouput:
![carbon](https://user-images.githubusercontent.com/4921147/31906999-dad5c0c4-b832-11e7-9e40-e72134565271.png)

Second edit:
```cmd
C:\Users\sebastian>node -v
8.7.0

C:\Users\sebastian>npm -v
5.4.2

C:\Users\sebastian>vue -V
2.9.1

C:\Users\sebastian>vue init nuxt-community/nuxt-micro-template numi
```

The index,vue:
![image](https://user-images.githubusercontent.com/4921147/31909173-7d4eac16-b839-11e7-832d-73bae8cb0818.png)

I also updated npm againt to 5.5.1 but i can not replicate your issue

**Comment by vuchl** [comment]
@mickdekkers did you make any discoveries? Or can I close the issue?

**Comment by mickdekkers** [comment]
@vuchl I'm afraid I haven't. As a workaround I just copied the missing code from the repo directly. Feel free to close 🙂
